// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5uUlRCLxS6m1kq_iGQs6NLoagCQ3qmcc',
    appId: '1:991212627103:web:653f3b961682ca3895aeaa',
    messagingSenderId: '991212627103',
    projectId: 'dear-49a5e',
    authDomain: 'dear-49a5e.firebaseapp.com',
    storageBucket: 'dear-49a5e.appspot.com',
    measurementId: 'G-3NWYPEW0X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr4GUwH9zIQH0qHAiRyVz1Be3MN0zCF4c',
    appId: '1:991212627103:android:50bdc3caa7d53bd095aeaa',
    messagingSenderId: '991212627103',
    projectId: 'dear-49a5e',
    storageBucket: 'dear-49a5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTv6aJj47JvHZ5abk-xwFp9iVcw0z-2WU',
    appId: '1:991212627103:ios:8c749813954304ad95aeaa',
    messagingSenderId: '991212627103',
    projectId: 'dear-49a5e',
    storageBucket: 'dear-49a5e.appspot.com',
    iosBundleId: 'kr.hs.dgsw.dearApp',
  );

}